name: Deep Fuzz
on:
  push:
    branches:
      - development
    paths:
      - '**.sol'

jobs:
  deep-fuzz:
    name: Deep Fuzz
    runs-on: ubuntu-22.04
    env:
      FOUNDRY_PROFILE: intense

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-ddca274340319fbd264dfa019a6de2a8146f50f6

      - name: Forge install
        working-directory: packages/contracts
        run: forge install

      - name: Deep Fuzz Solidity Contracts
        working-directory: packages/contracts
        run: forge test
