name: "Kebab Case CI"
on:
  push:
    branches:
      - '*'
  pull_request:
jobs:
  kebab-case-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Verify file names
      run: |
        failed_files=$(find . -not -path './.git/*' -type f -name '*[A-Z]*' -printf '%f\n')
        if [[ $failed_files ]]; then
          echo "The following files have uppercase letters in their names:"
          echo "$failed_files"
          exit 1
        fi
