name: "Kebab Case CI"
on:
  push:
    branches:
      - main
jobs:
  kebab-case-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Verify file names
      run: |
        if [[ $(find . -not -path './.git/*' -type f -name '*[A-Z]*' -printf 1) ]]; then
          echo "Files with uppercase letters detected. Please rename the files to kebab-case format."
          exit 1
        fi
